/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/registerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/roleSelection`; params?: Router.UnknownInputParams; } | { pathname: `/owner/chat`; params?: Router.UnknownInputParams; } | { pathname: `/owner/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/dashboard` | `/owner/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/listings` | `/owner/listings`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/profile` | `/owner/profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/requests` | `/owner/requests`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step1`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step2`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step3`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/loginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/registerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/resetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/roleSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/owner${'/(tabs)'}/dashboard` | `/owner/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/owner${'/(tabs)'}/listings` | `/owner/listings`; params?: Router.UnknownOutputParams; } | { pathname: `/owner${'/(tabs)'}/profile` | `/owner/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/owner${'/(tabs)'}/requests` | `/owner/requests`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/create-listing/step1`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/create-listing/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/owner/create-listing/step3`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/loginScreen${`?${string}` | `#${string}` | ''}` | `/auth/registerScreen${`?${string}` | `#${string}` | ''}` | `/auth/resetPassword${`?${string}` | `#${string}` | ''}` | `/auth/roleSelection${`?${string}` | `#${string}` | ''}` | `/owner/chat${`?${string}` | `#${string}` | ''}` | `/owner/editProfile${`?${string}` | `#${string}` | ''}` | `/owner${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/owner/dashboard${`?${string}` | `#${string}` | ''}` | `/owner${'/(tabs)'}/listings${`?${string}` | `#${string}` | ''}` | `/owner/listings${`?${string}` | `#${string}` | ''}` | `/owner${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/owner/profile${`?${string}` | `#${string}` | ''}` | `/owner${'/(tabs)'}/requests${`?${string}` | `#${string}` | ''}` | `/owner/requests${`?${string}` | `#${string}` | ''}` | `/owner/create-listing/step1${`?${string}` | `#${string}` | ''}` | `/owner/create-listing/step2${`?${string}` | `#${string}` | ''}` | `/owner/create-listing/step3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/registerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/resetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/roleSelection`; params?: Router.UnknownInputParams; } | { pathname: `/owner/chat`; params?: Router.UnknownInputParams; } | { pathname: `/owner/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/dashboard` | `/owner/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/listings` | `/owner/listings`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/profile` | `/owner/profile`; params?: Router.UnknownInputParams; } | { pathname: `/owner${'/(tabs)'}/requests` | `/owner/requests`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step1`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step2`; params?: Router.UnknownInputParams; } | { pathname: `/owner/create-listing/step3`; params?: Router.UnknownInputParams; };
    }
  }
}
